SELECT * FROM DBA_TABLESPACES;
SELECT * FROM DBA_DATA_FILES;

ALTER TABLESPACE DATA1 ALTER DATAFILE 'C:\USERS\HOTUNG\APP\ORADATA\ORCL\DATA100.DBF' SIZE 200M  AUTOEXTEND ON NEXT 1M MAXSIZE 500M;
ALTER DATABASE DATAFILE 'C:\USERS\HOTUNG\APP\ORADATA\ORCL\DATA100.DBF' AUTOEXTEND ON NEXT 1M MAXSIZE 500M;
ALTER DATABASE DATAFILE 'C:\USERS\HOTUNG\APP\ORADATA\ORCL\DATA100.DBF' RESIZE 20M;